### ISSUE TITLE
zi[0] used but not initialized

### ISSUE THREAD

**Issue by busyyang** [nxsEdson/Butterworth-Filter#1]
Hello, thanks for your good work. But I guess there is some problem, you used zi[0] with non-initialization in `filter` function. 
```	else
	{
		for (int m = 0; m<len_x; m++)
		{
			filter_x[m] = coeff_b[0] * x[m] + zi[0];
			for (int i = 1; i<len_b; i++)
			{
				zi[i - 1] = coeff_b[i] * x[m] + zi[i] - coeff_a[i] * filter_x[m];
			}
		}
	}
```

**Comment by nxsEdson** [comment]
The vector is initialized by the constructor. All the elements are initialized to zero.

**Comment by busyyang** [comment]
thanks for answer the vector question. But I also noticed the output vector `filter_x` is only involved in the calculation of coeff_b[0]. In the inner for-loop, only zi[i-1] updated, but `filter_x` is not updated. Could you please fix this problem?
